# Generated by Django 5.0 on 2024-03-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id',
            new_name='usuario_id',
        ),
    ]
