# Generated by Django 5.0 on 2024-03-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_rename_id_usuarios_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuario_id',
            new_name='id',
        ),
    ]
