# Generated by Django 5.0.3 on 2024-03-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_rename_usuario_id_usuarios_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=20)),
                ('duracion', models.IntegerField()),
                ('creditos', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
    ]
