# Generated by Django 5.0.3 on 2024-03-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_cursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='id_curso',
            new_name='idcurso',
        ),
    ]
